---
title: "README"
output: md_document
date: "2024-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A Package for Annotating Panospheric (360-degree) Images in R - Example Files

This repository contains:

1.  The full code required to generate related panels and analyses presented the accompanying paper. To use it please clone the repository and then open the project pannotator_examples_gituhb.Rproj in RStudio. All code is provided in the associated pannotator_examples.qmd file (quarto must be installed). All data files required are provided in the Data_file folder.\
    A web version of the markdown file is available here: [pannotator_examples.md](pannotator_examples.md)

2.  The complete data validation study files including Supporting Information 3. All code is provided in the associated pannotator_data_validation.qmd file (quarto must be installed). All data files required are provided in the Data_file folder.\
    A web version of the markdown file is available here: [pannotator_data_validation.md](pannotator_data_validation.md)
